SET DEFINE OFF;
Insert into GENRES (ID,GENRE) values ('1','Alternative');
Insert into GENRES (ID,GENRE) values ('2','Blues');
Insert into GENRES (ID,GENRE) values ('3','Blues/R&B');
Insert into GENRES (ID,GENRE) values ('4','Comedy');
Insert into GENRES (ID,GENRE) values ('5','Electronic');
Insert into GENRES (ID,GENRE) values ('6','Folk');
Insert into GENRES (ID,GENRE) values ('7','Hard Rock');
Insert into GENRES (ID,GENRE) values ('8','Heavy Metal');
Insert into GENRES (ID,GENRE) values ('9','Hip-Hop');
Insert into GENRES (ID,GENRE) values ('10','Industrial');
Insert into GENRES (ID,GENRE) values ('11','Pop');
Insert into GENRES (ID,GENRE) values ('12','Progressive Metal');
Insert into GENRES (ID,GENRE) values ('13','Punk');
Insert into GENRES (ID,GENRE) values ('14','Punk Rock');
Insert into GENRES (ID,GENRE) values ('15','Rap');
Insert into GENRES (ID,GENRE) values ('16','Rock');
Insert into GENRES (ID,GENRE) values ('17','Schlager');
Insert into GENRES (ID,GENRE) values ('18','Ska');
Insert into GENRES (ID,GENRE) values ('19','Soundtrack');
Insert into GENRES (ID,GENRE) values ('20','Thrash Metal');
Insert into GENRES (ID,GENRE) values ('21','Death Metal');
Insert into GENRES (ID,GENRE) values ('22','Ambient');
Insert into GENRES (ID,GENRE) values ('23','New Metal');
Insert into GENRES (ID,GENRE) values ('24','Black Metal');
Insert into GENRES (ID,GENRE) values ('25','Klassik');
Insert into GENRES (ID,GENRE) values ('26','Mashup');
Insert into GENRES (ID,GENRE) values ('27','Grindcore');
Insert into GENRES (ID,GENRE) values ('28','Crossover');
Insert into GENRES (ID,GENRE) values ('29','Gothic Metal');
Insert into GENRES (ID,GENRE) values ('30','Grunge');
Insert into GENRES (ID,GENRE) values ('31','Country');
Insert into GENRES (ID,GENRE) values ('32','Swing');
Insert into GENRES (ID,GENRE) values ('33','Hörbuch & Gesprochene Inhalte');
Insert into GENRES (ID,GENRE) values ('34','Murder Metal');
Insert into GENRES (ID,GENRE) values ('35','Reggae');
Insert into GENRES (ID,GENRE) values ('36','Soul');
Insert into GENRES (ID,GENRE) values ('37','Big Band');
Insert into GENRES (ID,GENRE) values ('38','Techno');
Insert into GENRES (ID,GENRE) values ('39','Trance');
Insert into GENRES (ID,GENRE) values ('40','House');
Insert into GENRES (ID,GENRE) values ('41','Jazz');
Insert into GENRES (ID,GENRE) values ('42','A Cappella');
Insert into GENRES (ID,GENRE) values ('44','Latin');
Insert into GENRES (ID,GENRE) values ('45','Pagan Metal');
Insert into GENRES (ID,GENRE) values ('46','R&B');
Insert into GENRES (ID,GENRE) values ('50','Filmmusik');
Insert into GENRES (ID,GENRE) values ('51','Disco');
Insert into GENRES (ID,GENRE) values ('54','Singer/Songwriter');
Insert into GENRES (ID,GENRE) values ('55','Podcast');
Insert into GENRES (ID,GENRE) values ('56','Weltmusik');
Insert into GENRES (ID,GENRE) values ('58','Musik für Kinder');
Insert into GENRES (ID,GENRE) values ('61','Unknown');
Insert into GENRES (ID,GENRE) values ('62','Acid Jazz');
Insert into GENRES (ID,GENRE) values ('63','Dance');
Insert into GENRES (ID,GENRE) values ('64','Steampunk');
Insert into GENRES (ID,GENRE) values ('65','Vocal');
Insert into GENRES (ID,GENRE) values ('66','SynthPop');
Insert into GENRES (ID,GENRE) values ('67','Raï');
Insert into GENRES (ID,GENRE) values ('68','Southern Rock');
Insert into GENRES (ID,GENRE) values ('69','Gothic Rock');
Insert into GENRES (ID,GENRE) values ('70','New Wave');
Insert into GENRES (ID,GENRE) values ('71','Psychadelic');
Insert into GENRES (ID,GENRE) values ('72','Progressive Rock');
Insert into GENRES (ID,GENRE) values ('73','BritPop');
Insert into GENRES (ID,GENRE) values ('74','Space');
Insert into GENRES (ID,GENRE) values ('75','Metalcore');
Insert into GENRES (ID,GENRE) values ('76','Hardcore Punk');
Insert into GENRES (ID,GENRE) values ('77','Trip-Hop');
Insert into GENRES (ID,GENRE) values ('78','Psychedelic Rock');
Insert into GENRES (ID,GENRE) values ('79','Big Beat');
Insert into GENRES (ID,GENRE) values ('80','Alternative Rock');
Insert into GENRES (ID,GENRE) values ('81','Funk');
Insert into GENRES (ID,GENRE) values ('82','Horrorcore');
Insert into GENRES (ID,GENRE) values ('83','Jazz Fusion');
Insert into GENRES (ID,GENRE) values ('84','Acid House');
Insert into GENRES (ID,GENRE) values ('85','Rock and roll');
Insert into GENRES (ID,GENRE) values ('87','Classic Rock');
Insert into GENRES (ID,GENRE) values ('88','Folk Rock');
Insert into GENRES (ID,GENRE) values ('89','Art Rock');
Insert into GENRES (ID,GENRE) values ('90','Rockabilly');
Commit;